// Copyright (c) 2013-2016 The btcsuite developers
// Copyright (c) 2026 Blink Labs Software
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

package bloom_test

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"testing"
	"time"

	"github.com/blinklabs-io/handshake-node/blockchain"
	"github.com/blinklabs-io/handshake-node/chaincfg/chainhash"
	"github.com/blinklabs-io/handshake-node/hnsutil"
	"github.com/blinklabs-io/handshake-node/hnsutil/bloom"
	"github.com/blinklabs-io/handshake-node/wire"
)

// TestMerkleBlockHSDVector combines three canonical Handshake transactions to
// cover matched raw leaves, domain-separated unmatched leaves, internal nodes,
// and hsd's empty sentinel for a missing right branch.  The expected payload
// was generated by hsd commit 9f013c1cb7f92edf94db69fbd69daf34adf655fb.
func TestMerkleBlockHSDVector(t *testing.T) {
	block := newHSDVectorBlock(t)
	wantRoot := mustHash(t,
		"e1a611b962cd68a69e05c07b61acc1a71c5dec1a90cfe4341410b617612aece7",
	)
	if got := block.MsgBlock().Header.MerkleRoot; got != *wantRoot {
		t.Fatalf("merkle root = %s, want %s", got, wantRoot)
	}

	filter := bloom.LoadFilter(wire.NewMsgFilterLoad(
		make([]byte, 64),
		10,
		0x12345678,
		wire.BloomUpdateNone,
	))
	filter.AddHash(block.Transactions()[1].Hash())

	merkleBlock, matched := bloom.NewMerkleBlock(block, filter)
	if want := []uint32{1}; !reflect.DeepEqual(matched, want) {
		t.Fatalf("matched indexes = %v, want %v", matched, want)
	}

	wantHashes := []*chainhash.Hash{
		mustHash(t, "8e4c9756fef2ad10375f360e0560fcc7587eb5223ddf8cd7c7e06e60a1140b15"),
		mustHash(t, "43b23ae794eadf72f42cc2997fa9aa5b59acc39eeab45ff26bdba2e6cb53d950"),
		mustHash(t, "a9942d0b7cfa816fa845a0ea2c7dec2dba1be345d44fd5b9fa6dde01a6a1c12d"),
	}
	if !reflect.DeepEqual(merkleBlock.Hashes, wantHashes) {
		t.Fatalf("partial hashes = %v, want %v", merkleBlock.Hashes, wantHashes)
	}
	if wantFlags := []byte{0x0b}; !bytes.Equal(merkleBlock.Flags, wantFlags) {
		t.Fatalf("flags = %x, want %x", merkleBlock.Flags, wantFlags)
	}

	wantPayload, err := hex.DecodeString(
		"0000000000000000000000000000000000000000000000000000000000000000" +
			"0000000000000000000000000000000000000000000000000000000000000000" +
			"0000000000000000000000000000000000000000000000000000000000000000" +
			"0000000000000000000000000000000000000000000000000000000000000000" +
			"0000000000000000000000000000000000000000000000000000000000000000" +
			"00000000" +
			"e1a611b962cd68a69e05c07b61acc1a71c5dec1a90cfe4341410b617612aece7" +
			"0000000000000000000000000000000000000000000000000000000000000000" +
			"000000000000000003000000038e4c9756fef2ad10375f360e0560fcc7587eb5" +
			"223ddf8cd7c7e06e60a1140b1543b23ae794eadf72f42cc2997fa9aa5b59acc3" +
			"9eeab45ff26bdba2e6cb53d950a9942d0b7cfa816fa845a0ea2c7dec2dba1be3" +
			"45d44fd5b9fa6dde01a6a1c12d010b",
	)
	if err != nil {
		t.Fatalf("decode hsd merkle-block vector: %v", err)
	}

	var gotPayload bytes.Buffer
	if err := merkleBlock.BtcEncode(
		&gotPayload,
		wire.ProtocolVersion,
		wire.LatestEncoding,
	); err != nil {
		t.Fatalf("encode merkle block: %v", err)
	}
	if !bytes.Equal(gotPayload.Bytes(), wantPayload) {
		t.Fatalf(
			"encoded merkle block = %x, want hsd vector %x",
			gotPayload.Bytes(),
			wantPayload,
		)
	}
}

func newHSDVectorBlock(t *testing.T) *hnsutil.Block {
	t.Helper()

	msgBlock := &wire.MsgBlock{}
	txs := make([]*hnsutil.Tx, 0, 3)
	for i := 0; i < 3; i++ {
		path := filepath.Join(
			"..",
			"..",
			"blockchain",
			"testdata",
			"handshake",
			fmt.Sprintf("block_%d.raw", i),
		)
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		fixture, err := hnsutil.NewBlockFromBytes(raw)
		if err != nil {
			t.Fatalf("decode %s: %v", path, err)
		}
		if got := len(fixture.MsgBlock().Transactions); got != 1 {
			t.Fatalf("%s contains %d transactions, want 1", path, got)
		}

		msgTx := fixture.MsgBlock().Transactions[0].Copy()
		msgBlock.Transactions = append(msgBlock.Transactions, msgTx)
		txs = append(txs, hnsutil.NewTx(msgTx))
	}

	msgBlock.Header.Timestamp = time.Unix(0, 0).UTC()
	msgBlock.Header.MerkleRoot = blockchain.CalcMerkleRoot(txs, false)
	return hnsutil.NewBlock(msgBlock)
}

func mustHash(t *testing.T, value string) *chainhash.Hash {
	t.Helper()
	hash, err := chainhash.NewHashFromStrStrict(value)
	if err != nil {
		t.Fatalf("parse hash %q: %v", value, err)
	}
	return hash
}
