name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  GO_VERSION: 1.26.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0 https://github.com/actions/checkout/releases/tag/v7.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0 https://github.com/actions/setup-go/releases/tag/v6.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            go.sum
            hnsutil/go.sum
            hnsutil/psbt/go.sum
      - name: golangci-lint
        run: make lint workers=2
